"""add_missing_fk_indexes

Revision ID: 0bc173deee7b
Revises: 
Create Date: 2026-06-09 06:05:42.210186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bc173deee7b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_allergies_patient_id'), 'allergies', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_appointment_time'), 'appointments', ['appointment_time'], unique=False)
    op.create_index(op.f('ix_appointments_appointment_type_id'), 'appointments', ['appointment_type_id'], unique=False)
    op.create_index(op.f('ix_appointments_doctor_id'), 'appointments', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_documents_encounter_id'), 'documents', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_documents_patient_id'), 'documents', ['patient_id'], unique=False)
    op.create_index(op.f('ix_documents_uploaded_by'), 'documents', ['uploaded_by'], unique=False)
    op.create_index(op.f('ix_encounters_appointment_id'), 'encounters', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_encounters_doctor_id'), 'encounters', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_encounters_patient_id'), 'encounters', ['patient_id'], unique=False)
    op.create_index(op.f('ix_immunizations_administered_by'), 'immunizations', ['administered_by'], unique=False)
    op.create_index(op.f('ix_immunizations_patient_id'), 'immunizations', ['patient_id'], unique=False)
    op.create_index(op.f('ix_insurances_patient_id'), 'insurances', ['patient_id'], unique=False)
    op.create_index(op.f('ix_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoices_appointment_id'), 'invoices', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_invoices_patient_id'), 'invoices', ['patient_id'], unique=False)
    op.create_index(op.f('ix_lab_results_catalog_id'), 'lab_results', ['catalog_id'], unique=False)
    op.create_index(op.f('ix_lab_results_encounter_id'), 'lab_results', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_lab_results_ordered_by'), 'lab_results', ['ordered_by'], unique=False)
    op.create_index(op.f('ix_lab_results_ordered_date'), 'lab_results', ['ordered_date'], unique=False)
    op.create_index(op.f('ix_lab_results_patient_id'), 'lab_results', ['patient_id'], unique=False)
    op.create_index(op.f('ix_medical_problems_patient_id'), 'medical_problems', ['patient_id'], unique=False)
    op.create_index(op.f('ix_medications_patient_id'), 'medications', ['patient_id'], unique=False)
    op.create_index(op.f('ix_medications_prescribed_by'), 'medications', ['prescribed_by'], unique=False)
    op.create_index(op.f('ix_messages_patient_id'), 'messages', ['patient_id'], unique=False)
    op.create_index(op.f('ix_messages_receiver_id'), 'messages', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_messages_status'), 'messages', ['status'], unique=False)
    op.create_index(op.f('ix_patient_ai_summaries_id'), 'patient_ai_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_patient_ai_summaries_patient_id'), 'patient_ai_summaries', ['patient_id'], unique=False)
    op.drop_constraint('patient_ai_summaries_patient_id_fkey', 'patient_ai_summaries', type_='foreignkey')
    op.create_foreign_key(None, 'patient_ai_summaries', 'patients', ['patient_id'], ['id'])
    op.create_index(op.f('ix_patient_vitals_encounter_id'), 'patient_vitals', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_patient_vitals_vital_config_id'), 'patient_vitals', ['vital_config_id'], unique=False)
    op.create_index(op.f('ix_prescription_items_prescription_id'), 'prescription_items', ['prescription_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_date_prescribed'), 'prescriptions', ['date_prescribed'], unique=False)
    op.create_index(op.f('ix_prescriptions_doctor_id'), 'prescriptions', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_encounter_id'), 'prescriptions', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_patient_id'), 'prescriptions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_template_items_template_id'), 'template_items', ['template_id'], unique=False)
    op.create_index(op.f('ix_user_tabs_user_id'), 'user_tabs', ['user_id'], unique=False)
    op.create_index(op.f('ix_visit_complaints_encounter_id'), 'visit_complaints', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_visit_diagnoses_encounter_id'), 'visit_diagnoses', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_visit_treatments_encounter_id'), 'visit_treatments', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_vitals_patient_id'), 'vitals', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vitals_patient_id'), table_name='vitals')
    op.drop_index(op.f('ix_visit_treatments_encounter_id'), table_name='visit_treatments')
    op.drop_index(op.f('ix_visit_diagnoses_encounter_id'), table_name='visit_diagnoses')
    op.drop_index(op.f('ix_visit_complaints_encounter_id'), table_name='visit_complaints')
    op.drop_index(op.f('ix_user_tabs_user_id'), table_name='user_tabs')
    op.drop_index(op.f('ix_template_items_template_id'), table_name='template_items')
    op.drop_index(op.f('ix_prescriptions_patient_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_encounter_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_doctor_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_date_prescribed'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescription_items_prescription_id'), table_name='prescription_items')
    op.drop_index(op.f('ix_patient_vitals_vital_config_id'), table_name='patient_vitals')
    op.drop_index(op.f('ix_patient_vitals_encounter_id'), table_name='patient_vitals')
    op.drop_constraint(None, 'patient_ai_summaries', type_='foreignkey')
    op.create_foreign_key('patient_ai_summaries_patient_id_fkey', 'patient_ai_summaries', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_patient_ai_summaries_patient_id'), table_name='patient_ai_summaries')
    op.drop_index(op.f('ix_patient_ai_summaries_id'), table_name='patient_ai_summaries')
    op.drop_index(op.f('ix_messages_status'), table_name='messages')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_receiver_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_patient_id'), table_name='messages')
    op.drop_index(op.f('ix_medications_prescribed_by'), table_name='medications')
    op.drop_index(op.f('ix_medications_patient_id'), table_name='medications')
    op.drop_index(op.f('ix_medical_problems_patient_id'), table_name='medical_problems')
    op.drop_index(op.f('ix_lab_results_patient_id'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_ordered_date'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_ordered_by'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_encounter_id'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_catalog_id'), table_name='lab_results')
    op.drop_index(op.f('ix_invoices_patient_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_appointment_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoice_items_invoice_id'), table_name='invoice_items')
    op.drop_index(op.f('ix_insurances_patient_id'), table_name='insurances')
    op.drop_index(op.f('ix_immunizations_patient_id'), table_name='immunizations')
    op.drop_index(op.f('ix_immunizations_administered_by'), table_name='immunizations')
    op.drop_index(op.f('ix_encounters_patient_id'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_doctor_id'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_appointment_id'), table_name='encounters')
    op.drop_index(op.f('ix_documents_uploaded_by'), table_name='documents')
    op.drop_index(op.f('ix_documents_patient_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_encounter_id'), table_name='documents')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_doctor_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_type_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_time'), table_name='appointments')
    op.drop_index(op.f('ix_allergies_patient_id'), table_name='allergies')
    # ### end Alembic commands ###
